version: '3.7'
services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DATABASE=appDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
